db:
  image: postgres
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "80:8000"
  environment:
    - DATABASE_URL=postgres://postgres@db:5432/postgres
  links:
    - db
